In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
a=pd.read_csv("/content/movies.csv")
a

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en

In [ ]:
a.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton


In [ ]:
a.tail()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger


In [ ]:
a.describe()

,index,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4803.000000,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2401.000000,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,1386.651002,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,1200.500000,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,2401.000000,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,3601.500000,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,4802.000000,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000


In [ ]:
a.isna().sum()

,0
index,0
budget,0
genres,28
homepage,3091
id,0
keywords,412
original_language,0
original_title,0
overview,3
popularity,0


In [ ]:
selected_features=[['genres', 'keywords', 'overview', 'tagline',
    'cast', 'crew', 'director',
    'original_language', 'production_companies']]
print(selected_features)

[['genres', 'keywords', 'overview', 'tagline', 'cast', 'crew', 'director', 'original_language', 'production_companies']]


In [ ]:
for features in selected_features:
  a[features]=a[features].fillna('')

In [ ]:
a.isna().sum()

,0
index,0
budget,0
genres,0
homepage,3091
id,0
keywords,0
original_language,0
original_title,0
overview,0
popularity,0


In [ ]:
combined_features=a['genres'] + " "+a['keywords'] + " " +a['overview'] + " " +a['tagline'] + " " +a['cast'] + " " +a['crew'] + " " +a['director'] + " " +a  ['original_language'] + " " +a['production_companies']
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      When ambitious New York attorney Sam is sent...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [ ]:
Vectorizer=TfidfVectorizer()
feature_Vectors=Vectorizer.fit_transform(combined_features)
print(feature_Vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 996504 stored elements and shape (4803, 244592)>
  Coords	Values
  (0, 186801)	0.004825380491830039
  (0, 186992)	0.005533097640181004
  (0, 203828)	0.006881837446232598
  (0, 232083)	0.006401932703740933
  (0, 204342)	0.006431364212963073
  (0, 198427)	0.011733279136863442
  (0, 196350)	0.01252999988333295
  (0, 205737)	0.008910548165641666
  (0, 234649)	0.019631971541062953
  (0, 242214)	0.0069862992257703855
  (0, 196879)	0.013861331139354179
  (0, 234300)	0.01071817778838601
  (0, 211318)	0.002869104008924103
  (0, 237650)	0.006703076828755089
  (0, 40232)	0.015948431050286253
  (0, 195275)	0.01510010016283622
  (0, 225085)	0.015578854390604137
  (0, 218981)	0.01091137720213165
  (0, 211974)	0.003368149340894707
  (0, 200585)	0.014543380412478648
  (0, 238141)	0.0025065713163557922
  (0, 221623)	0.011201451139193198
  (0, 224952)	0.026703803636129484
  (0, 224115)	0.003967993019166691
  (0, 240539)	0.012456280501546575
 

In [ ]:
similarity=cosine_similarity(feature_Vectors)
print(similarity)

[[1.         0.57149841 0.82378638 ... 0.32149326 0.07027812 0.15042344]
 [0.57149841 1.         0.5773803  ... 0.2918391  0.06646764 0.13645755]
 [0.82378638 0.5773803  1.         ... 0.33560969 0.07949596 0.15342024]
 ...
 [0.32149326 0.2918391  0.33560969 ... 1.         0.05754167 0.09754641]
 [0.07027812 0.06646764 0.07949596 ... 0.05754167 1.         0.03913374]
 [0.15042344 0.13645755 0.15342024 ... 0.09754641 0.03913374 1.        ]]


In [ ]:
movie_name=input("enter your favourite movie name: ")

enter your favourite movie name: spiderman


In [ ]:
list_of_all_titles=a['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
import difflib

find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
close_match=find_close_match[0]
print(close_match)

Spider-Man


In [ ]:
close_match=find_close_match[0]
print(close_match)

Spider-Man


In [ ]:
index_of_movie=a[a.title==close_match]['index'].values[0]
print(index_of_movie)

159


In [ ]:
similarity_score=list(enumerate(similarity[index_of_movie]))
print(similarity_score)

[(0, np.float64(0.7750358605031135)), (1, np.float64(0.5979317493571651)), (2, np.float64(0.7830307511151049)), (3, np.float64(0.8152921766259272)), (4, np.float64(0.7680130412294288)), (5, np.float64(0.698065420169283)), (6, np.float64(0.6451244389367256)), (7, np.float64(0.716009380046413)), (8, np.float64(0.5573654234091814)), (9, np.float64(0.7633750858124586)), (10, np.float64(0.49057843691769315)), (11, np.float64(0.42933778185992216)), (12, np.float64(0.5311742733916058)), (13, np.float64(0.5602051607092136)), (14, np.float64(0.6678475432030593)), (15, np.float64(0.7180369148395971)), (16, np.float64(0.7723334542155061)), (17, np.float64(0.6034460245292395)), (18, np.float64(0.46923816765310045)), (19, np.float64(0.7695106627057448)), (20, np.float64(0.7602213694158527)), (21, np.float64(0.47290596482107)), (22, np.float64(0.7617308107735355)), (23, np.float64(0.5808202399525324)), (24, np.float64(0.6205174286214881)), (25, np.float64(0.6601503656733598)), (26, np.float64(0.7790

In [ ]:
sorted_similar_movies=sorted(similarity_score,key=lambda i:i[1], reverse=True)
print(sorted_similar_movies)

[(159, np.float64(0.9999999999999993)), (28, np.float64(0.8284955996177774)), (412, np.float64(0.821171470861197)), (212, np.float64(0.8207475509619122)), (30, np.float64(0.8171206921635241)), (185, np.float64(0.8164578558524825)), (3, np.float64(0.8152921766259272)), (365, np.float64(0.8150821547497604)), (171, np.float64(0.8137400628892065)), (1430, np.float64(0.8131944386366732)), (303, np.float64(0.812091339482068)), (298, np.float64(0.8117842896405413)), (186, np.float64(0.8115748778268601)), (165, np.float64(0.811490846525877)), (275, np.float64(0.8105894632917329)), (654, np.float64(0.8081683004177918)), (505, np.float64(0.808041182517937)), (150, np.float64(0.8076723222470985)), (112, np.float64(0.8061502486842526)), (93, np.float64(0.8060290155093195)), (1823, np.float64(0.8057782138638039)), (529, np.float64(0.8044690895421597)), (1133, np.float64(0.8039461255375097)), (583, np.float64(0.8039413308795215)), (568, np.float64(0.803866028219206)), (828, np.float64(0.803533210042

In [ ]:
print("movies suggested for you : \i")

i=1

for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=a[a.index==index]['title'].values[0]
  if(i<30):
    print(i, '.',title_from_index)
    i=i=1

<>:1: SyntaxWarning: invalid escape sequence '\i'
<>:1: SyntaxWarning: invalid escape sequence '\i'
/tmp/ipython-input-2008502279.py:1: SyntaxWarning: invalid escape sequence '\i'
  print("movies suggested for you : \i")


movies suggested for you : \i
1 . Spider-Man
1 . Jurassic World
1 . The Core
1 . The Day After Tomorrow
1 . Spider-Man 2
1 . War of the Worlds
1 . The Dark Knight Rises
1 . Contact
1 . Master and Commander: The Far Side of the World
1 . Cursed
1 . Catwoman
1 . The Wolf of Wall Street
1 . Bad Boys II
1 . Hulk
1 . Minority Report
1 . Blade: Trinity
1 . The League of Extraordinary Gentlemen
1 . Men in Black II
1 . Alexander
1 . Terminator 3: Rise of the Machines
1 . Freddy vs. Jason
1 . Tears of the Sun
1 . 15 Minutes
1 . Big Fish
1 . xXx
1 . Kill Bill: Vol. 1
1 . Blade II
1 . A.I. Artificial Intelligence
1 . The Aviator
1 . The Bourne Supremacy
1 . Harry Potter and the Prisoner of Azkaban
1 . The Alamo
1 . The Chronicles of Riddick
1 . Harry Potter and the Chamber of Secrets
1 . Ant-Man
1 . Collateral
1 . End of Days
1 . The Polar Express
1 . I, Robot
1 . Blade
1 . Collateral Damage
1 . Batman Begins
1 . Black Hawk Down
1 . The Fast and the Furious
1 . Harry Potter and the Philosopher's 